# -*- coding: utf-8 -*-

SALE_ORDER_KEYS = [
    ['{{today}}', 'Today formart as dd/mm/yyyy'],
    ['{{today_date}}', 'The day of current date'],
    ['{{today_month}}', 'The month of current date'],
    ['{{today_year}}', 'The year of current date'],
    ['{{sale_name}}', 'Sale order name'],
    ['{{user_name}}', 'Salesperson'],
    ['{{partner_name}}', 'Customer'],
    ['{{partner_address}}', 'Customer Address'],
    ['{{partner_phone}}', 'Customer phone'],
    ['{{partner_email}}', 'Customer email'],
    ['{{partner_vat}}', 'Customer vat'],
    ['{{date_order}}', 'Quotation Date'],
    ['{{validity_date}}', 'Expiration Date'],
    ['{{payment_term}}', 'Payment Terms'],
    ['{{amount_untaxed}}', 'Untaxed Amount'],
    ['{{amount_tax}}', 'Taxes'],
    ['{{total_price}}', 'Total Amount'],
    ['{{amount_in_words}}', 'Amount in words'],
    ['{{tbl_contents}}', 'Order Table'],
    ['{{line_index}}', 'Line index'],
    ['{{product_name}}', 'Product name'],
    ['{{line_description}}', 'Description'],
    ['{{product_unit}}', 'Product Unit'],
    ['{{product_qty}}', 'Product Quanity'],
    ['{{line_unit_price}}', 'Unit Price'],
    ['{{tax_name}}', 'Taxes Name'],
    ['{{line_price_subtotal}}', 'Line Price Subtotal'],
]
